services:
  - type: web
    name: raostudios-portfolio
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --keep-alive 60 --max-requests 1000 --preload app:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: raostudios-db
          property: connectionString
    autoDeploy: true

databases:
  - name: raostudios-db
    databaseName: raostudios
    user: raostudios_user 